name: example
description: Data Over Audio Example
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.1.5"
  flutter: "3.13.9"

dependencies:
  flutter:
    sdk: flutter

  mrumru:
    path: ../

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: 8.1.3
  bloc_test: 9.1.4
  
  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5
  
  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: 7.6.4
  
  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: 2.0.2+1

  # A Flutter plugin to play multiple simultaneously audio files, works for Android, iOS, Linux, macOS, Windows, and web.
  # https://pub.dev/packages/audioplayers
  audioplayers: 5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: 2.4.6

flutter:
  uses-material-design: true