name: mrumru
description: Data Over Audio
version: 0.0.10
publish_to: 'none'

environment:
  sdk: ">=3.2.6"
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: 2.0.5
  
  # This is a simple Service Locator for Dart and Flutter projects.
  # https://pub.dev/packages/get_it
  get_it: 7.6.7
  
  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: 2.4.0

  # Implementations of SHA, MD5, and HMAC cryptographic functions.
  # https://pub.dev/packages/crypto
  crypto: 3.0.3

  # Simple tools for reading and writing WAV and raw audio files.
  # https://pub.dev/packages/wav
  wav: 1.3.0

  # A Flutter plugin for multi-platform, simple audio stream playback with real-time generated audio data streams.
  # https://pub.dev/packages/mp_audio_stream
  mp_audio_stream: 0.1.5

  # A wrapper class for Isolate that exposes a communication channel using a Stream.
  # https://pub.dev/packages/stream_isolate
  stream_isolate: 0.2.0

  # Audio recorder from microphone to a given file path.
  # Fork of: https://pub.dev/packages/record
  record:
    git:
      url: https://github.com/CandyLabsIT/record.git
      ref: fork-master
      path: record

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: 2.4.6

flutter:
  uses-material-design: true
