name: mrumru
description: Data Over Audio
version: 0.0.1

environment:
  sdk: ">=3.1.5"
  flutter: "^3.13.9"

dependencies:
  flutter:
    sdk: flutter

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5
  
  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: ^7.6.4
  
  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: ^2.0.2+1

  # A Flutter plugin to play multiple simultaneously audio files, works for Android, iOS, Linux, macOS, Windows, and web.
  # https://pub.dev/packages/audioplayers
  audioplayers: ^5.2.0

  # Audio recorder from microphone to a given file path.
  # https://pub.dev/packages/record
  record: ^5.0.1

  # A Flutter plugin for finding commonly used locations on the filesystem. Supports Android, iOS, Linux, macOS and Windows. Not all methods are supported on all platforms.
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.1

  # Implementations of SHA, MD5, and HMAC cryptographic functions.
  # https://pub.dev/packages/crypto
  crypto: ^3.0.3

  # Simple tools for reading and writing WAV and raw audio files.
  # https://pub.dev/packages/wav
  wav: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
